# This is Jeopardy!

#### Overview

This project is slightly different than others you have encountered thus far. Instead of a step-by-step tutorial, this project contains a series of open-ended requirements which describe the project you'll be building. There are many possible ways to correctly fulfill all of these requirements, and you should expect to use the internet, Codecademy, and/or other resources when you encounter a problem that you cannot easily solve.

#### Project Goals

You will work to write several functions that investigate a dataset of _Jeopardy!_ questions and answers. Filter the dataset for topics that you're interested in, compute the average difficulty of those questions, and train to become the next Jeopardy champion!

## Prerequisites

In order to complete this project, you should have completed the Pandas lessons in the <a href="https://www.codecademy.com/learn/paths/analyze-data-with-python">Analyze Data with Python Skill Path</a>. You can also find those lessons in the <a href="https://www.codecademy.com/learn/data-processing-pandas">Data Analysis with Pandas course</a> or the <a href="https://www.codecademy.com/learn/paths/data-science/">Data Scientist Career Path</a>.

Finally, the <a href="https://www.codecademy.com/learn/practical-data-cleaning">Practical Data Cleaning</a> course may also be helpful.

## Project Requirements

1. We've provided a csv file containing data about the game show _Jeopardy!_ in a file named `jeopardy.csv`. Load the data into a DataFrame and investigate its contents. Try to print out specific columns.

   Note that in order to make this project as "real-world" as possible, we haven't modified the data at all - we're giving it to you exactly how we found it. As a result, this data isn't as "clean" as the datasets you normally find on Codecademy. More specifically, there's something odd about the column names. After you figure out the problem with the column names, you may want to rename them to make your life easier for the rest of the project.
   
   In order to display the full contents of a column, we've added this line of code for you:
   
   ```py
   pd.set_option('display.max_colwidth', None)
   ```

In [24]:
import pandas as pd
import re

pd.set_option('display.max_colwidth', None)

df = pd.read_csv('jeopardy.csv')
df = df.rename(columns={
    "Show Number":"id",
    " Air Date":"date",
    " Round":"round",
    " Category":"category",
    " Value":"value",
    " Question":"question",
    " Answer":"answer"
})

df['value'] = df['value'].str.replace('$','').str.replace(',', '').str.replace('no value', '0').astype(float)
print(df.head())

     id        date      round                         category  value  \
0  4680  2004-12-31  Jeopardy!                          HISTORY  200.0
1  4680  2004-12-31  Jeopardy!  ESPN's TOP 10 ALL-TIME ATHLETES  200.0
2  4680  2004-12-31  Jeopardy!      EVERYBODY TALKS ABOUT IT...  200.0
3  4680  2004-12-31  Jeopardy!                 THE COMPANY LINE  200.0
4  4680  2004-12-31  Jeopardy!              EPITAPHS & TRIBUTES  200.0

                                                                                                      question  \
0             For the last 8 years of his life, Galileo was under house arrest for espousing this man's theory
1  No. 2: 1912 Olympian; football star at Carlisle Indian School; 6 MLB seasons with the Reds, Giants & Braves
2                     The city of Yuma in this state has a record average of 4,055 hours of sunshine each year
3                         In 1963, live on "The Art Linkletter Show", this company served its billionth burger
4     Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States

       answer
0  Copernicus
1  Jim Thorpe
2     Arizona
3  McDonald's
4  John Adams

2. Write a function that filters the dataset for questions that contains all of the words in a list of words. For example, when the list `["King", "England"]` was passed to our function, the function returned a DataFrame of 49 rows. Every row had the strings `"King"` and `"England"` somewhere in its `" Question"`.

   Test your function by printing out the column containing the question of each row of the dataset.

In [25]:
questions = df['question']

def filter_question_by_list_of_words(word_list):
    return df[df["question"].apply(
        lambda question: all(word.lower() in question.lower() for word in word_list)
    )]

my_list = ['Constitution', 'Mass']

filter_question_by_list_of_words(my_list)

,id,date,round,category,value,question,answer
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,200.0,"Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States",John Adams
83954,3114,1998-02-26,Double Jeopardy!,THE U.S.S. CONSTITUTION,800.0,"Like fellow Mass. heavyweight Rocky Marciano, the Constitution won over 30 fights & lost this many",no value
146398,5671,2009-04-13,Jeopardy!,SAM ADAMS,1000.0,In June 1776 Adams was selected as Massachusetts' lone delegate to help draft this first U.S. Constitution,the Articles of Confederation
189101,3129,1998-03-19,Double Jeopardy!,AFTER THEY LEFT OFFICE,400.0,"In 1820 at age 85, he served as a delegate at Massachusetts' Constitutional Convention",John Adams

3. Test your original function with a few different sets of words to try to find some ways your function breaks. Edit your function so it is more robust.

   For example, think about capitalization. We probably want to find questions that contain the word `"King"` or `"king"`.
   
   You may also want to check to make sure you don't find rows that contain substrings of your given words. For example, our function found a question that didn't contain the word `"king"`, however it did contain the word `"viking"` &mdash; it found the `"king"` inside `"viking"`. Note that this also comes with some drawbacks &mdash; you would no longer find questions that contained words like `"England's"`.

In [34]:
def filter_question_exact_match(word_list):
    return df[df["question"].apply(
        lambda question: all(
         re.search(rf"\b{re.escape(word)}\b", question) for word in word_list)   
    )]

my_pick = ['President', 'United']

filter_question_exact_match(my_pick)

,id,date,round,category,value,question,answer
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,200.0,"Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States",John Adams
9730,4738,2005-03-23,Double Jeopardy!,ROUGH POLITICS,1200.0,"A N.Y. coroner's inquest came to a finding of murder by this man, Vice President of the United States",Aaron Burr
10811,5437,2008-04-08,Double Jeopardy!,THE GERALD R. FORD MUSEUM,1200.0,"(<a href=""http://www.j-archive.com/media/2008-04-08_DJ_20.jpg"" target=""_blank"">Cheryl stands next to a large ornate plate.</a>) This beautiful <a href=""http://www.j-archive.com/media/2008-04-08_DJ_20a.jpg"" target=""_blank"">Kutani</a> plate was presented to President Ford in 1975 by this emperor, the first from his country ever to visit the United States",Hirohito
13427,4726,2005-03-07,Jeopardy!,WORLD LEADERS: 1871,200.0,In 1871 this man was President of the United States,Ulysses Grant
17584,731,1987-11-09,Double Jeopardy!,WORLD WAR I,200.0,"The United States never ratified the Versailles treaty, though this President played a key role in drafting it",Woodrow Wilson
19618,5459,2008-05-08,Double Jeopardy!,LET'S VISIT THE MIDEAST,2000.0,"(<a href=""http://www.j-archive.com/media/2008-05-08_DJ_10.jpg"" target=""_blank"">Cheryl of the Clue Crew indicates a map of the Middle East on the monitor.</a>) In 1958 the spell of President Nasser's Pan-Arab Movement persuaded this country to join Egypt in the United Arab Republic",Syria
76176,3733,2000-11-22,Jeopardy!,THE ROARING '20s,400.0,"On August 3, 1923 at 2:47 A.M. he was sworn in as President of the United States by his father",Calvin Coolidge
81312,4559,2004-06-03,Double Jeopardy!,"PEOP""L""",1200.0,"President of the United Mine Workers for 40 years, he helped found the CIO in 1935",(John L.) Lewis
86528,4630,2004-10-22,Double Jeopardy!,THE HISTORY OF DISNEYLAND,800.0,"<a href=""http://www.j-archive.com/media/2004-10-22_DJ_14.jpg"" target=""_blank"">This</a> man, who co-hosted the grand opening of Disneyland, later became the President of the United States",Ronald Reagan
110073,4093,2002-05-22,Double Jeopardy!,BEFORE & AFTER,400.0,Melville's great white whale who's the current Vice President of the United States,Moby Dick Cheney
174524,3275,1998-11-27,Jeopardy!,THE PREZ SEZ,200.0,"""I'm President of the United States, and I'm not going to eat any more broccoli!""",George H.W. Bush
191767,4257,2003-02-18,Double Jeopardy!,HISTORY SPEAKS!,400.0,(George Washington) These are the two cities in which I was inaugurated President of the United States,New York & Philadelphia
211816,3800,2001-02-23,Jeopardy!,"BRANSON, HANSON OR MANSON",500.0,"As president under the Articles of Confederation, he's sometimes called ""The First President of the United States""",John Hanson

4. We may want to eventually compute aggregate statistics, like `.mean()` on the `" Value"` column. But right now, the values in that column are strings. Convert the`" Value"` column to floats. If you'd like to, you can create a new column with float values.

   While most of the values in the `" Value"` column represent a dollar amount as a string, note that some do not &mdash; these values will need to be handled differently!

   Now that you can filter the dataset of question, use your new column that contains the float values of each question to find the "difficulty" of certain topics. For example, what is the average value of questions that contain the word `"King"`?
   
   Make sure to use the dataset that contains the float values as the dataset you use in your filtering function.

In [37]:
def calculate_average_value(word_list):
    filtered_df = filter_question_exact_match(word_list)
    return filtered_df['value'].mean()
    

my_choice = ['Constitution']

avg_value = calculate_average_value(my_choice)

print(f'The average value for questions with the words {my_choice} is {avg_value:.2f} points')

The average value for questions with the words ['Constitution'] is 805.00 points

5. Write a function that returns the count of unique answers to all of the questions in a dataset. For example, after filtering the entire dataset to only questions containing the word `"King"`, we could then find all of the unique answers to those questions. The answer "Henry VIII" appeared 55 times and was the most common answer.

6. Explore from here! This is an incredibly rich dataset, and there are so many interesting things to discover. There are a few columns that we haven't even started looking at yet. Here are some ideas on ways to continue working with this data:

 * Investigate the ways in which questions change over time by filtering by the date. How many questions from the 90s use the word `"Computer"` compared to questions from the 2000s?
 * Is there a connection between the round and the category? Are you more likely to find certain categories, like `"Literature"` in Single Jeopardy or Double Jeopardy?
 * Build a system to quiz yourself. Grab random questions, and use the <a href="https://docs.python.org/3/library/functions.html#input">input</a> function to get a response from the user. Check to see if that response was right or wrong.

## Solution

7. Compare your program to our <a href="https://content.codecademy.com/PRO/independent-practice-projects/jeopardy/jeopardy_solution.zip">sample solution code</a> - remember, that your program might look different from ours (and probably will) and that's okay!

8. Great work! Visit <a href="https://discuss.codecademy.com/t/this-is-jeopardy-challenge-project-python-pandas/462365">our forums</a> to compare your project to our sample solution code. You can also learn how to host your own solution on GitHub so you can share it with other learners! Your solution might look different from ours, and that's okay! There are multiple ways to solve these projects, and you'll learn more by seeing others' code.